# name: churn-example
channels:
  - defaults
  - conda-forge
dependencies:
  - pip:
       - -e git+https://github.com/Avitqwak/churn_test.git#egg=churn_test
       - churn_test
  - python=3.8
  - pip=19.3.1
  - pandas=1.1.5
  - scikit-learn=0.24
  - catboost=0.24.3
